[0m22:18:37.183237 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262E0B78C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262DECF0B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262E1C4FED0>]}


============================== 22:18:37.188813 | 668b9c6a-ad01-4dd1-b65e-b9cca2e9e586 ==============================
[0m22:18:37.188813 [info ] [MainThread]: Running with dbt=1.9.1
[0m22:18:37.189528 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jonsan\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m22:22:53.814803 [debug] [MainThread]: Starter project path: C:\Users\jonsan\Test_Knowit_Gbg\venv\Lib\site-packages\dbt\include\starter_project
[0m22:22:53.842726 [info ] [MainThread]: 
Your new dbt project "test_knowit_gbg" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:22:53.845177 [info ] [MainThread]: Setting up your profile.
[0m22:23:14.049699 [debug] [MainThread]: Command `dbt init` succeeded at 22:23:14.049503 after 277.00 seconds
[0m22:23:14.050083 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262E1C6E8B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262E1E1EE70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000262E1D118C0>]}
[0m22:23:14.050433 [debug] [MainThread]: Flushing usage events
[0m22:23:14.487191 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:05:03.558443 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F68C38C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F66DB0B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F69D17ED0>]}


============================== 23:05:03.564675 | 8926dabc-2df2-41ba-b592-0dbbe63c4435 ==============================
[0m23:05:03.564675 [info ] [MainThread]: Running with dbt=1.9.1
[0m23:05:03.565611 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\jonsan\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m23:05:03.566211 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jonsan\Test_Knowit_Gbg\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m23:05:03.568070 [debug] [MainThread]: Command `dbt run` failed at 23:05:03.567877 after 0.22 seconds
[0m23:05:03.568592 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F69D35220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F69C3A0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021F69BE5AE0>]}
[0m23:05:03.569163 [debug] [MainThread]: Flushing usage events
[0m23:05:04.094253 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:56:34.962705 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E7888C20>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E59FCB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E896FED0>]}


============================== 15:56:34.968885 | 58664219-2c30-46fb-b2a0-ef48dd217f52 ==============================
[0m15:56:34.968885 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:56:34.969779 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\jonsan\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m15:56:34.970240 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\jonsan\Test_Knowit_Gbg\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:56:34.971327 [debug] [MainThread]: Command `dbt run` failed at 15:56:34.971220 after 0.15 seconds
[0m15:56:34.971620 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E8985220>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E888A0F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000152E8835AE0>]}
[0m15:56:34.972019 [debug] [MainThread]: Flushing usage events
[0m15:56:35.481081 [debug] [MainThread]: An error was encountered while trying to flush usage events
